H_001 - As regards the conditions of use of what is provided via this page or the related APIs, the documents in the 'files' section and the ebooks (that have specific additional payments and requirements), these are the terms and conditions briefly set out :
	<ul>
		<li>Use for your personal life - OK - No mandatory payment required</li>
		<li>Use for experimentation, writing and sale of books or ebooks on one's experiences in this regard - OK</li>
		<li>Use for development and sharing of content that develops these concepts more broadly by integrating other information or opinions - OK (no mandatory payment from the user should be required, but advertising from other companies to earn money is allowed OR a one-time or subscription payment may be required, but advertising must not be present)</li>
		<li>Used to carry out translations to be provided free of charge via the internet - OK (link the source)</li>
		<li>Use to carry out translations to be provided for a fee via the internet - NO</li>
		<li>Use to carry out translations to be provided on paper - NO</li>
		<li>Use for large projects - I recommend contacting me via email and paying a 1% to 3% monthly royalty on all earnings if the project is approved (also variable from month to month, your choice)</li>
		<li>Use to create harmful projects or companies towards this company - NO</li>
		<li>Use to create projects or companies from scratch towards this company - Royalties to be paid from 1% up to 15% on all earnings (of your choice also variable from month to month)</li>
		<li>Use in existing companies for modifications or improvements to existing products or services - Guarantees are offered only upon payment of royalties ranging from 1% to 3% (of your choice also variable from month to month)</li>
	</ul>
	<br />
	If you have any doubts about the terms and conditions you can contact this company via email. As regards the payment of any arrears, you can comply (at your choice and in a variable manner) within 6 months of reading the following terms and conditions and pay monthly for subsequent periods. 
	Carrying out litter picking (both marine and terrestrial), planting flowers, plants or trees (through donations or volunteering) is considered a valid form of payment, creating freely accessible abstract works of art using rocks, metals, drawings or paints is considered a valid form of payment (through donations or volunteering). The use of wood or its derivatives for works of art in the absence of substitute materials is considered 'neutral' (only of the material). Creating multimedia elements (images, films, videos, software, texts or other) and making them available and usable without requiring payment is considered a form of payment at 50% towards this company. The voluntary donation of valuable natural and raw minerals shipped to the company's home COULD and SHOULD ensure new developments and improved services (subject to acceptance via email). In the event of the death of the legal representative of this company, he or she is chosen in the person over 18 years old and with the highest IQ that can be found (man or woman, of any nationality). Anything not specified or even deriving from free personal initiatives of those who use these contents is treated with common sense. In addition to this, the final amount to be paid can be multiplied by the customer's choice by a fraction among the following: 1/2, 1/3, 1/4, 1/5 or 1/6. In any case, both the chosen percentage and the fraction must be expressly communicated and are in any case variable from month to month at the customer's choice.
	In addition to this, what is written in the "Philosophy" section can also be expressly used by the Vatican without any type of authorization from me, as conceptually, despite being a "philosophy box", it was still created starting from the other box, and it is therefore believed that this one (called "Aelion" is positioned inside that other [Catholic Church]). In addition to this, as far as the European Union is concerned, the principle of friendship applies to any nation within it, which allows its use even free of charge in the event of very serious problems due to armed conflicts still in progress or recently happened, and which in this case, even with regards to e-books, the terms and conditions present in the description are not to be considered as mandatory to be respected.