<hr /> <!-- 299 -->
    <span class="red">
    A299 - Cos&igrave; come in natura esistono rampicanti capaci di consumare i semi prodotti da certi alberi (ad esempio l'edera intorno alla quercia) cos&igrave; pu&ograve; avvenire anche per le persone. Ci sono donne, tipicamente anche molto giovani che seguono un'alimentazione vegana o fruttariana, che per lavoro (retribuito) possono assumersi il compito di avere rapporti sessuali con uomini molto pi&ugrave; grandi di loro e che hanno una pessima reputazione (per i loro reati causati dal mangiar carne, requisito obbligatorio ...) senza l'uso del preservativo. Come avviene spesso che l'edera riesca facilmente ad alimentarsi delle ghiande della quercia e che crescendo uccida l'albero, avviso lo stesso pu&ograve; avvenire anche per queste persone. In caso di morte della persona pi&ugrave; anziana tutti i beni posseduti in vita vanno ceduti alla lavoratrice. Oltre a questo, come servizio separato, se hanno il seno molto sviluppato possono farsi palpeggiare il seno (anche per 1-2 ore se riescono). Potrebbe non essere piacevole, chiaramente, ma se riuscite a sopportare la fatica e lo stress o il cliente lo desidera allora comunque state facendo un lavoro. In ogni caso la scelta di concedere questo tipo di servizi &egrave; a loro discrezione, cos&igrave; come l'eventuale importo da far pagare al cliente. In generale comunque il prezzo pu&ograve; variare in base a come si decide di calibrare la situazione (scelta di determinati atteggiamenti mentali, la frequenza con cui si fanno questi lavori, il luogo, il bisogno di un supporto esterno). Eventualmente potete anche offrire sedute di meditazione in cui si rimane seduti a guardarsi negli occhi se vi sentite preparate. Per quanto riguarda queste attivit&agrave; sappiate comunque che il colore dei capelli, della pelle o altre particolarit&agrave; (es. tatuaggi, anelli, gioielli, braccialetti) possono in determinati casi aiutare o essere necessari per raggiungere un determinato obiettivo. Se decidete di fare questo tipo di lavoro indossare un ciondolo a forma di cerchio come segno di riconoscimento (potete usare anche una rondella se siete povere) viene considerato valido a partire dal 1 marzo 2024. (attenzione, pu&ograve; essere pericoloso e potrebbe essere necessario anche il supporto di una persona che pratica la castit&agrave; di sesso opposto per far si che la persona adulta di sesso femminile rimanga sufficientemente in salute). Per quanto riguarda, analogamente, gli uomini con gli organi sessuali molto muscolosi, stesso discorso pu&ograve; valere per loro, in modo similare. Nota : non &egrave; detto che le opinioni sui social network di queste persone siano per&ograve; intelligenti, in quando scientificamente parlando l'uso frequente degli organi sessuali tendenzialmente diminuisce l'intelligenza in quanto si consumano ingenti risorse chimiche del corpo.
    </span> 
    <hr /> <!-- 300 -->
    <span class="red">
    A300 - Se delle ragazzine in giovane et&agrave; non ancora fertili (requisito necessario) e che sono cresciute fin dalla nascita o da almeno 6 anni consecutivi con alimentazione vegana o fruttariana desiderano in un qualche modo sviluppare meglio la propria sessualit&agrave; esiste la possibilit&agrave; di chiedere a degli uomini adulti col pene molto sviluppato, anche con una pessima reputazione causata dal loro mangiar carne (requisito obbligatorio) di essere stuprate da loro (anche eventualmente dietro compenso per l'uomo). Naturalmente &egrave; comunque necessario che l'uomo si comporti delicatamente e che si lasci anche guidare dalla giovane adolescente. In caso di morte dell'uomo adulto dopo lo stupro tutti i beni posseduti dallo stupratore vanno ceduti alla giovane adolescente. Ci tengo a precisare che entrambe queste procedure (A299 e A300) sono frutto di ragionamenti molto ponderati e in questo caso la similitudine &egrave; quella del fiore di loto. E' possibile concettualmente anche utilizzare dei carcerati, e in quel caso il pagamento &egrave; di un numero di entrate alle terme o di una breve vacanza a scelta della giovane (in entrambi i casi dovr&agrave; essere sorvegliato da un poliziotto). In entrambi i casi il pagamento eventualmente da effettuare viene concordato PRIMA, ed &egrave; obbligatoria la visione integrale di un film horror da parte dell'uomo prima del rapporto, e di altrettanto tempo all'incirca facendo meditazione anche con le necessarie tracce musicali da parte della giovane adolescente (in parallelo). La persona pi&ugrave; giovane, terminata l'esperienza, deve concedersi il necessario riposo o meditazione fino a quando non &egrave; di nuovo in ottima salute. (attenzione, pu&ograve; essere pericoloso e potrebbe essere necessario anche il supporto di una persona che pratica la castit&agrave; di sesso opposto per far passare il trauma al giovane)
    </span>
    <hr /> <!-- 301 -->
    <span class="red">
    A301 - Se delle ragazzine in giovane et&agrave; non ancora fertili che per&ograve; sono state educate facendo loro mangiare la carne vogliono in un qualche modo essere aiutate a cambiare rotta in modo molto marcato psicologicamente in modo da riuscire a diventare stabilmente vegane o fruttariane, possono chiedere di effettuare delle sessioni di tantra (dietro pagamento se possibile) con degli uomini vegani o fruttariani che abbiano praticato la castit&agrave; per diversi anni. In ogni caso, se &egrave; la minore a farne richiesta o a sentirne il bisogno, &egrave; concettualmente possibile lasciarle fare rapporti sessuali con uomini adulti di sua scelta. Alcune donne si sviluppano meglio in questo modo.
    </span>
    <hr /> <!-- 302 -->
    <span class="red">
    A302 - Se dei ragazzini in giovane et&agrave; non ancora fertili che per&ograve; sono stati educati facendo loro mangiare la carne vogliono in un qualche modo essere aiutati a cambiare rotta in modo molto marcato psicologicamente in modo da riuscire a diventare stabilmente vegani o fruttariani, possono chiedere di effettuare delle sessioni di tantra (dietro pagamento quando possibile) con delle donne vegane o fruttariane che abbiano praticato la castit&agrave; per diversi anni. In questo caso sono particolarmente indicate le donne con la vagina grande. In entrambi casi (A301 e A302) non c'&egrave; nessun rapporto "classico" vero e proprio, semplicemente ci si "aggancia" e si rimane ad aspettare in osservazione per il tempo necessario. &Egrave; anche consentito l'uso di cristalli di quarzo o profumi a supporto, o eventualmente anche altri minerali. Queste procedure (A301 e A302) si possono usare anche pi&ugrave; volte (consiglio di scegliere sempre persone diverse) e quando l'adolescente si sente sufficientemente stabile mentalmente e mantiene un'alimentazione corretta, &egrave; possibile usare le procedure A300 e A303 (seguendo le relative istruzioni). 
    </span>
    <hr /> <!-- 303 -->
    <span class="red">
    A303 - Se dei ragazzini in giovane et&agrave; non ancora fertili (requisito necessario) e sono cresciuti fin dalla nascita o da almeno 6 anni consecutivi con alimentazione vegana o fruttariana desiderano in un qualche modo sviluppare meglio la propria sessualit&agrave; esiste la possibilit&agrave; di chiedere a delle donne adulte col seno molto sviluppato, anche con una pessima reputazione causata dal loro mangiar carne (requisito obbligatorio) di essere stuprati da loro (anche eventualmente dietro compenso per la donna). &Egrave; necessario che la donna cerchi di seguire le indicazioni del giovane. In caso di morte della donna adulta dopo lo stupro tutti i suoi beni vengono assegnati al giovane. E' possibile concettualmente anche utilizzare delle carcerate, e in quel caso il pagamento &egrave; di un numero di entrate alle terme o di una breve vacanza a scelta dal giovane (in entrambi i casi dovr&agrave; essere sorvegliata da una poliziotta). In entrambi i casi il pagamento eventualmente da effettuare viene concordato PRIMA, ed &egrave; obbligatoria la visione integrale di un film horror da parte della donna prima del rapporto, e di altrettanto tempo all'incirca facendo meditazione anche con le necessarie tracce musicali da parte del giovane adolescente (in parallelo). La persona pi&ugrave; giovane, terminata l'esperienza, deve concedersi il necessario riposo o meditazione fino a quando non &egrave; di nuovo in ottima salute (consiglio ad esempio l'uso della meditazione mantenendo la mano appoggiata alle parti "inquinate"). Sia per le procedure A300 e A303 se necessario, per stare tranquilli, &egrave; possibile comunque usare anche dei contraccettivi o prodotti lubrificanti, ma nessun preservativo, e l'uso obbligatorio per l'uomo di un prodotto con le caratteristiche tipiche del Viagra. Naturalmente servono luoghi adeguati e potrebbe servire anche la supervisione di un/una infermiera. (attenzione, pu&ograve; essere pericoloso e potrebbe essere necessario anche il supporto di una persona che pratica la castit&agrave; di sesso opposto per far passare il trauma al giovane)
    </span>
    <hr /> <!-- 304 -->
    <span class="red">
    A304 - Per quanto riguarda il percorso di crescita dei nuovi nascituri consiglio alle famiglie, oltre all'alimentazione vegana o fruttariana per l'adolescente, anche l'utilizzo delle procedure A300 e A303 (anche in base alle scelte dell'adolescente). Raggiunta la maturit&agrave; sessuale, consiglio di mantenere la castit&agrave; fino al termine degli studi. Se si riesce, consiglio anche di mantenere la castit&agrave; fino al compimento dei 30 anni di et&agrave;. Se decidete di utilizzare pi&ugrave; volte le procedure A300 e A303, consiglio di scegliere sempre persone diverse per quanto possibile, ma comunque fate attenzione perch&eacute; probabilmente sono piuttosto pericolose.
    </span>
    -------
    <hr /> <!-- 320 -->
    A320 - Per quanto riguarda gli aborti, se sia l'uomo che la donna che hanno effettuato il concepimento ritengono che sia meglio non proseguire la gravidanza e interromperla con metodi pi&ugrave; o meno dolorosi, e se ritengono che quella sia la scelta pi&ugrave; intelligente e giusta (per motivi che al momento non mi dilungo a spiegare) e se ne assumono la responsabilit&agrave; e se il feto viene rigorosamente sepolto sotto terra (requisito obbligatorio), allora non ci sono problemi ad utilizzarlo. Il feto morto sepolto, concettualmente, &egrave; concime anche quello. In ogni caso questa procedura &egrave; piuttosto rischiosa e faticosa, quindi in ogni caso raccomando prudenza. Non &egrave; neppure detto che lo scopo del concepimento in se non sia semplicemente, per partito preso, la produzione di concime organico, ma se decidete di effettuare questo tipo di lavoro siate molto chiari nel vostro intento e fatelo presente anche alla comunit&agrave;. Se ci si pensa, anche noi come specie piantiamo alberi col solo scopo di produrre del legname.