H_001 - Per quanto riguarda le condizioni d'uso di quanto fornito tramite questa pagina o le relative API, i documenti nella sezione files e gli ebooks (che hanno pagamenti e requisiti addizionali), questi sono i termini e condizioni esposti brevemente :
<ul>
	<li>Utilizzo per la propria vita personale - OK - Nessun pagamento obbligatorio richiesto</li>
	<li>Utilizzo per sperimentazioni, scrittura e vendita di libri o ebook sulle proprie esperienze in merito - OK</li>
	<li>Utilizzo per sviluppo e la condivisione di contenuti che sviluppano questi concetti in modo pi&ugrave; ampio integrando altre informazioni o opinioni - OK (non dev'essere richiesto il pagamento obbligatorio da parte dell'utente, ma la pubblicit&agrave; da altre aziende per guadagnare soldi &egrave; consentita OPPURE pu&ograve; essere richiesto un pagamento una tantum o in abbonamento, ma non deve essere presente la pubblicit&agrave;)</li>
	<li>Utilizzo per effettuare traduzioni da fornire gratuitamente tramite internet - OK (linkate la fonte)</li>
	<li>Utilizzo per effettuare traduzioni da fornire a pagamento tramite internet - NO</li>
	<li>Utilizzo per effettuare traduzioni da fornire su supporto cartaceo - NO</li>
	<li>Utilizzo per grandi progetti - Consiglio di contattarmi tramite email e di pagare una royalty dall'1% al 3% su tutti i guadagni se il progetto viene approvato (anche variabili di mese in mese, a vostra scelta)</li>
	<li>Utilizzo per creare progetti o aziende lesive nei confronti di questa azienda - NO</li>
	<li>Utilizzo per creare progetti o aziende ex-novo - Royalties da pagare ALMENO dell'1% e FINO A UN MASSIMO DEL 15% su tutti i guadagni (a vostra scelta anche variabile di mese in mese)</li>
	<li>Utilizzo in aziende gi&agrave; esistenti per modifiche o miglioramenti a prodotti o servizi gi&agrave; esistenti - Si offrono garanzie solo dietro il pagamento di royalties variabili dall'1% al 3% sui guadagni dell'azienda (a vostra scelta anche variabile di mese in mese)</li>
</ul>
<br />
In caso di dubbi sui termini e condizioni potete contattare questa azienda tramite email (solo grandi enti religiosi o governativi). Per quanto riguarda il pagamento di eventuali arretrati potete adeguarvi (a vostra scelta e in modo variabile) entro 6 mesi dalla lettura dei seguenti termini e condizioni e pagare mensilmente per i periodi successivi. Effettuare litterpicking (sia marino che terrestre), piantare fiori, piante o alberi (tramite donazioni o volontariato), creare opere d'arte astratte liberalmente fruibili tramite rocce, metalli, disegni o pitture &egrave; considerata una forma di pagamento valida (tramite donazioni o volontariato). L'uso di legno o dei suoi derivati per opere d'arte in mancanza di materiali sostitutivi &egrave; considerato 'neutrale' (solo del materiale). Creare elementi multimediali (immagini, film, video, software, testi o altro) e renderli disponibili e utilizzabili senza richiedere un pagamento &egrave; considerata una forma di pagamento al 50% nei confronti di questa azienda. La donazione volontaria di minerali naturali e grezzi di valore spediti al domicilio dell'azienda POTREBBE e DOVREBBE garantire nuovi sviluppi e migliori servizi (previa accettazione tramite email). In caso di morte del o della legale rappresentante di questa azienda, esso o essa viene scelta nella persona con pi&ugrave; di 18 anni e col pi&ugrave; alto QI che si riesce a reperire (uomo o donna, di qualunque nazionalit&agrave;). Quanto eventualmente non specificato o anche derivante da libere iniziative personali di chi utilizza questi contenuti viene trattato col buon senso. Oltre a questo l'importo finale da pagare pu&ograve; essere moltiplicato a scelta del cliente per una frazione tra le seguenti : 1/2, 1/3, 1/4, 1/5 o 1/6. In ogni caso sia la percentuale scelta che la frazione vanno espressamente comunicate e sono comunque variabili di mese in mese a scelta del cliente.
E' vietato qualsiasi utilizzo presente e futuro legato a sabotaggi di qualsivoglia tipo e genere.
Oltre a questo, quanto scritto nella sezione "Filosofia" &egrave; anche espressamente utilizzabile dal Vaticano senza nessun tipo di autorizzazione da parte mia, in quanto concettualmente, pur essendo una "scatola di filosofia" essa &egrave; stata comunque realizzata a partire dall'altra scatola, e si ritiene pertanto che questa (denominata "Aelion" sia posizionata all'interno di quell'altra [Chiesa Cattolica]). Oltre a questo, per quanto riguarda l'Unione Europea, si applica comunque il principio dell'amicizia applicato a qualsiasi nazione al suo interno che ne consente l'uso anche gratuito in caso di gravissime problematiche dovute a conflitti armati ancora in corso o recentemente avvenuti, e che in tal caso anche per quanto riguarda gli e-book i termini e condizioni presenti nella descrizione non sono da considerare come obbligatoriamente da rispettare.